MissionSite/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MissionSite.Controllers
{
    public class AboutUsController : Controller
    {
        // GET: AboutUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

MissionSite/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MissionSite.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

MissionSite/Views/AboutUs/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link href="~/myCSS/StyleSheet3.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/myCSS/StyleSheet2.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>About Us</title>
</head>

<body>
    <div class="w3-bar w3-black">
        <a href="@Url.Action("Index", "Home")" class="w3-bar-item w3-button"><b>Home</b></a>
        <a href="@Url.Action("Mission", "Home")" class="w3-bar-item w3-button">Missions</a>
        <a href="@Url.Action("Index", "AboutUs")" class="w3-bar-item w3-button">About Us</a>
        <a href="@Url.Action("Index", "Contact")" class="w3-bar-item w3-button">Contact</a>
        <a href="@Url.Action("Login", "Home")" class="w3-bar-item w3-button" style="float:right"><b>Log in</b></a>
        <a href="@Url.Action("SignUp", "Home")" class="w3-bar-item w3-button" style="float:right"><b>Sign Up</b></a>
    </div>

    <div class="row">
        <header class="business-header">
            <div class="col-md-12">
                <h1 class="display-3 mt-4" id="center">About Us</h1>
            </div>
        </header>
    </div>

    <div id="center">
        <h3 id="white">
            Our mission is to help future missionaries get their questions answered by
            those who have been to the mission! <br /> <br />
            If you're going on a mission, we would love to hear any questions you have! <br />
            And if you've gone on a mission we want to hear your advice!
        </h3>
    </div>


    <style>
        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

    </style>
    <div class="row">
        <img src="~/Content/waving missionaries.jpg" alt="Alternate Text" />
        </div>

</body>
</html>